"""Add user mobile fields (language, push_token, timezone)

Revision ID: 20668ac8d9fb
Revises: fa780bfb9a37
Create Date: 2025-10-26 19:19:15.965677

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20668ac8d9fb"
down_revision: Union[str, Sequence[str], None] = "fa780bfb9a37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("language", sa.String(), nullable=True))
    op.add_column("users", sa.Column("push_token", sa.String(), nullable=True))
    op.add_column("users", sa.Column("timezone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    op.drop_column("users", "push_token")
    op.drop_column("users", "language")
    # ### end Alembic commands ###
