"""Initial schema with users conversations messages and summaries

Revision ID: 32a82badeb9b
Revises:
Create Date: 2025-10-25 16:18:27.821107

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32a82badeb9b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("status", sa.Enum("ACTIVE", "COMPLETED", "ARCHIVED", name="conversationstatus"), nullable=False),
        sa.Column(
            "legal_area",
            sa.Enum("MIETRECHT", "ARBEITSRECHT", "VERTRAGSRECHT", "OTHER", name="legalarea"),
            nullable=True,
        ),
        sa.Column("case_strength", sa.Enum("STRONG", "MEDIUM", "WEAK", name="casestrength"), nullable=True),
        sa.Column("urgency", sa.Enum("IMMEDIATE", "WEEKS", "MONTHS", name="urgency"), nullable=True),
        sa.Column("current_agent", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_status"), "conversations", ["status"], unique=False)
    op.create_index("ix_conversations_user_created", "conversations", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_index("ix_conversations_user_status", "conversations", ["user_id", "status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("USER", "ASSISTANT", "SYSTEM", name="messagerole"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("agent_name", sa.String(length=50), nullable=True),
        sa.Column("function_call", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_messages_conversation_created", "messages", ["conversation_id", "created_at"], unique=False)
    op.create_index(op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False)
    op.create_table(
        "summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("markdown_content", sa.Text(), nullable=False),
        sa.Column("pdf_s3_key", sa.String(length=500), nullable=False),
        sa.Column("pdf_url", sa.String(length=1000), nullable=False),
        sa.Column(
            "legal_area",
            sa.Enum("MIETRECHT", "ARBEITSRECHT", "VERTRAGSRECHT", "OTHER", name="legalarea"),
            nullable=False,
        ),
        sa.Column("case_strength", sa.Enum("STRONG", "MEDIUM", "WEAK", name="casestrength"), nullable=False),
        sa.Column("urgency", sa.Enum("IMMEDIATE", "WEEKS", "MONTHS", name="urgency"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_summaries_conversation_id"), "summaries", ["conversation_id"], unique=True)
    op.create_index("ix_summaries_user_created", "summaries", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_summaries_user_id"), "summaries", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_summaries_user_id"), table_name="summaries")
    op.drop_index("ix_summaries_user_created", table_name="summaries")
    op.drop_index(op.f("ix_summaries_conversation_id"), table_name="summaries")
    op.drop_table("summaries")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_conversations_user_status", table_name="conversations")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index("ix_conversations_user_created", table_name="conversations")
    op.drop_index(op.f("ix_conversations_status"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
