"""Add documents table

Revision ID: 403149b5cfc9
Revises: 69548f077344
Create Date: 2025-12-13 16:33:20.252042

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "403149b5cfc9"
down_revision: Union[str, Sequence[str], None] = "69548f077344"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("file_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("s3_key", sa.String(length=1000), nullable=False),
        sa.Column("s3_url", sa.String(length=2000), nullable=False),
        sa.Column("upload_status", sa.Enum("UPLOADING", "COMPLETED", "FAILED", name="uploadstatus"), nullable=False),
        sa.Column(
            "ocr_status", sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="ocrstatus"), nullable=False
        ),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_index("ix_documents_conversation_created", "documents", ["conversation_id", "created_at"], unique=False)
    op.create_index(op.f("ix_documents_conversation_id"), "documents", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_documents_ocr_status"), "documents", ["ocr_status"], unique=False)
    op.create_index("ix_documents_upload_status", "documents", ["upload_status"], unique=False)
    op.create_index("ix_documents_user_created", "documents", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_documents_user_id"), "documents", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_user_id"), table_name="documents")
    op.drop_index("ix_documents_user_created", table_name="documents")
    op.drop_index("ix_documents_upload_status", table_name="documents")
    op.drop_index(op.f("ix_documents_ocr_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_conversation_id"), table_name="documents")
    op.drop_index("ix_documents_conversation_created", table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
