"""add_reference_number_and_markdown_s3_key_to_summaries

Revision ID: 69548f077344
Revises: 20668ac8d9fb
Create Date: 2025-12-13 13:37:33.928523

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69548f077344"
down_revision: Union[str, Sequence[str], None] = "20668ac8d9fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("summaries", sa.Column("reference_number", sa.String(length=50), nullable=True))
    op.add_column("summaries", sa.Column("markdown_s3_key", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("summaries", "markdown_s3_key")
    op.drop_column("summaries", "reference_number")
    # ### end Alembic commands ###
