"""Add notifications and lawyer_connections tables with metadata

Revision ID: 702377249055
Revises: 403149b5cfc9
Create Date: 2025-12-13 16:39:54.935725

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "702377249055"
down_revision: Union[str, Sequence[str], None] = "403149b5cfc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_read"), "notifications", ["read"], unique=False)
    op.create_index(op.f("ix_notifications_type"), "notifications", ["type"], unique=False)
    op.create_index("ix_notifications_user_created", "notifications", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_index("ix_notifications_user_read", "notifications", ["user_id", "read"], unique=False)
    op.create_table(
        "lawyer_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("summary_id", sa.UUID(), nullable=True),
        sa.Column("lawyer_id", sa.Integer(), nullable=False),
        sa.Column("lawyer_name", sa.String(length=200), nullable=True),
        sa.Column("user_message", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("lawyer_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["summary_id"], ["summaries.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_lawyer_connections_conversation", "lawyer_connections", ["conversation_id"], unique=False)
    op.create_index(
        op.f("ix_lawyer_connections_conversation_id"), "lawyer_connections", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_lawyer_connections_lawyer_id"), "lawyer_connections", ["lawyer_id"], unique=False)
    op.create_index(op.f("ix_lawyer_connections_status"), "lawyer_connections", ["status"], unique=False)
    op.create_index(op.f("ix_lawyer_connections_summary_id"), "lawyer_connections", ["summary_id"], unique=False)
    op.create_index("ix_lawyer_connections_user_created", "lawyer_connections", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_lawyer_connections_user_id"), "lawyer_connections", ["user_id"], unique=False)
    op.create_index("ix_lawyer_connections_user_status", "lawyer_connections", ["user_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lawyer_connections_user_status", table_name="lawyer_connections")
    op.drop_index(op.f("ix_lawyer_connections_user_id"), table_name="lawyer_connections")
    op.drop_index("ix_lawyer_connections_user_created", table_name="lawyer_connections")
    op.drop_index(op.f("ix_lawyer_connections_summary_id"), table_name="lawyer_connections")
    op.drop_index(op.f("ix_lawyer_connections_status"), table_name="lawyer_connections")
    op.drop_index(op.f("ix_lawyer_connections_lawyer_id"), table_name="lawyer_connections")
    op.drop_index(op.f("ix_lawyer_connections_conversation_id"), table_name="lawyer_connections")
    op.drop_index("ix_lawyer_connections_conversation", table_name="lawyer_connections")
    op.drop_table("lawyer_connections")
    op.drop_index("ix_notifications_user_read", table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_read"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
