"""Add conversation metadata for dynamic orchestration

Revision ID: fa780bfb9a37
Revises: 32a82badeb9b
Create Date: 2025-10-25 18:03:46.001579

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa780bfb9a37"
down_revision: Union[str, Sequence[str], None] = "32a82badeb9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable JSONB columns (no issues with existing rows)
    op.add_column("conversations", sa.Column("facts_collected", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("conversations", sa.Column("who", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("conversations", sa.Column("what", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("conversations", sa.Column("when", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("conversations", sa.Column("where", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("conversations", sa.Column("why", postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # Add boolean columns with server_default to handle existing rows
    op.add_column("conversations", sa.Column("analysis_done", sa.Boolean(), nullable=False, server_default="false"))
    op.add_column("conversations", sa.Column("summary_generated", sa.Boolean(), nullable=False, server_default="false"))

    # Remove server_default (we only needed it for migration)
    op.alter_column("conversations", "analysis_done", server_default=None)
    op.alter_column("conversations", "summary_generated", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "why")
    op.drop_column("conversations", "where")
    op.drop_column("conversations", "when")
    op.drop_column("conversations", "what")
    op.drop_column("conversations", "who")
    op.drop_column("conversations", "summary_generated")
    op.drop_column("conversations", "analysis_done")
    op.drop_column("conversations", "facts_collected")
    # ### end Alembic commands ###
